package main

func main() {
	// variableTest()
	// stringsTest()
	// arraysTest()
	// sliceTest()
	// mapTest()
	// constTest()
	// operatorTest()
	// dataTypeTest()
	// printScanTest()
	// ifElse()
	// forTest()
	// funcTest()
	// pointerTest()
	// structureTest()
	// structTest()
	pTest()
	// methodTest()
	// interfaceTest()
	// interfaceTest2()
	// interfaceNewTest()
	// controlStructureTest()
	// callTest()
	// importTest()
	// errorTest()
	// deferTest()
	// panicTest()
	// recoverTest()
	// goroutineTest()
	// channel1Test()
	// channel2Test()
	// wrongBufferedChannelTest()
	// bufferedChannelTest()
	// wrongChannelParamTest()
	// channelCloseTest()
	// channelRangeTest()
	// channelSelectTest()
}
